name: Publish ImmutaMap to NuGet

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
      - 'V*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version override (optional, matches csproj if empty)'
        required: false
        type: string

permissions:
  contents: read
  packages: write

env:
  PROJECT_PATH: ImmutaMap/ImmutaMap.csproj
  CONFIGURATION: Release
  # NuGet API key stored as a repository secret named NUGET_API_KEY

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Determine Version
        id: get_version
        shell: bash
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            VERSION=${{ github.event.inputs.version }}
          else
            VERSION=$(grep -oP '(?<=<Version>)[^<]+' ${{ env.PROJECT_PATH }} | head -n1)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION"

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c ${{ env.CONFIGURATION }} -p:ContinuousIntegrationBuild=true -p:Version=${{ steps.get_version.outputs.version }}

      - name: Pack
        run: dotnet pack ${{ env.PROJECT_PATH }} -c ${{ env.CONFIGURATION }} -p:PackageVersion=${{ steps.get_version.outputs.version }} --no-build --output ./artifacts

      - name: Publish to NuGet
        if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/V') || github.event_name == 'workflow_dispatch'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          if [ -z "$NUGET_API_KEY" ]; then
            echo 'NUGET_API_KEY secret not set'; exit 1; fi
          dotnet nuget push "./artifacts/*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ImmutaMap ${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          files: |
            artifacts/*.nupkg
